### ISSUE TITLE
Module is flagged as a System

### ISSUE THREAD

**Issue by DivertedCircle** [TheGoblinExplorer/foundryvtt-spell-checker#1]
See image.
![image](https://user-images.githubusercontent.com/26470570/109570935-175d0a80-7aa8-11eb-8e66-97b36c19fc92.png)

**Comment by TheGoblinExplorer** [comment]
Damn, thanks for notifying me. I'll fix it asap.

**Comment by TheGoblinExplorer** [comment]
@DivertedCircle It should be fixed, closing here, if it's still broken, please re-open this issue.
