### ISSUE TITLE
Module Breaks Compendium Linking

### ISSUE THREAD

**Issue by DivertedCircle** [TheGoblinExplorer/foundryvtt-spell-checker#2]
Having Speller enabled is breaking the ability to drag a compendium entry into a journal entry and having it link to the entry. Doing so with an actor from a compendium should give an entry that looks something like

@Compendium[world.beastiary.KcZPOBbEaefKlaYm]{Jorasco Alienist}

but it is instead showing up as

{"type":"Actor","pack":"world.beastiary","id":"Xm9nF4DPCCviRqnW"}.

It's also throwing the error below when it does so.

![image](https://user-images.githubusercontent.com/26470570/109672724-897a3180-7b32-11eb-8c53-b4535f0126c4.png)

**Comment by TheGoblinExplorer** [comment]
Thanks for notifying me of this, I'll work on a fix asap.

**Comment by TheGoblinExplorer** [comment]
It should be fixed with the latest release, please re-open if you still experience the issue.
